[versions]
kotlin = "1.8.21"
agp = "7.3.0"

android_minSdk = "21"
android_targetSdk = "33"
andorid_compileSdk = "33"

compose = "1.5.0-alpha03"
compose_compiler = "1.4.7"

room = "2.5.0-beta01"
media3 = "1.0.0-beta03"
ktor = "2.1.2"

[plugins]
agp = { id = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin_plugin = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
kotlin_coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.4" }

compose_foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose_ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose_animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose_ui_util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
compose_ripple = { module = "androidx.compose.material:material-ripple", version.ref = "compose" }
compose_activity = { module = "androidx.activity:activity-compose", version = "1.7.0-alpha01" }
compose_material3 = { module = "androidx.compose.material3:material3", version = "1.1.0-rc01"}
compose_shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version = "1.0.3" }
compose_coil = { module = "io.coil-kt:coil-compose", version = "2.2.2" }

room = { module = "androidx.room:room-ktx", version.ref = "room" }
room_compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }

ktor_client_core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor_client_cio = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor_client_content_negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor_client_encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor_client_serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor_serialization_json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

brotli = { module = "org.brotli:dec", version = "0.1.2" }
palette = { module = "androidx.palette:palette", version = "1.0.0" }

desugaring = { module = "com.android.tools:desugar_jdk_libs", version = "1.1.5" }

[bundles]
compose = [
    "compose_ui",
    "compose_ui_util",
    "compose_foundation",
    "compose_ui",
    "compose_animation",
    "compose_ripple",
    "compose_shimmer"
]